server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Wszystkie zapytania kierujemy na index.html (konieczne dla SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Blokada dostępu do ukrytych plików
    location ~ /\. {
        deny all;
    }
}
